language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
install:
- ". ./travis-ci/install-swagger-codegen.sh"
- openssl aes-256-cbc -K $encrypted_b0a304ce21a6_key -iv $encrypted_b0a304ce21a6_iv -in ./travis-ci/deploy_keys.enc -out ./travis-ci/deploy_keys.tar -d
- tar xvf ./travis-ci/deploy_keys.tar -C ./travis-ci/
script:
- "/bin/sh ./generate-sdks"
after_success:
- git config --global user.name "Travis CI"
- git config --global user.email "${TEAM_EMAIL}"
- "/bin/sh ./travis-ci/push-csharp-sdk.sh"
- "/bin/sh ./travis-ci/push-php-sdk.sh"
before_install:
- 
